spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/onlineshopdb"
        username: root
        password: admin@3104
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true